[build]
  command = "next build"
  publish = ".next"

[functions]
  included_files = ["node_modules/sharp/**/*"]

# Official Next.js on Netlify plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Retain your local image placeholder cache plugin if you still use it
[[plugins]]
  package = "/plugins/img-placeholder-cache"