[build]
  command = "next build"
  publish = ".next"

[functions]
  included_files = ["node_modules/sharp/**/*"]

# Official Next.js on Netlify plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

